export const SET_KANBAN_BOARD_UI_FLAG = 'SET_KANBAN_BOARD_UI_FLAG';
export const CLEAR_KANBAN_BOARDS = 'CLEAR_KANBAN_BOARDS';
export const SET_KANBAN_BOARDS = 'SET_KANBAN_BOARDS';
export const SET_KANBAN_BOARD_ITEM = 'SET_KANBAN_BOARD_ITEM';
export const EDIT_KANBAN_BOARD = 'EDIT_KANBAN_BOARD';
export const DELETE_KANBAN_BOARD = 'DELETE_KANBAN_BOARD';
export const SET_KANBAN_PREFERENCES = 'SET_KANBAN_PREFERENCES';
